{
 "title": "Docker Monitoring",
 "description": "Docker monitoring with Prometheus and cAdvisor",
 "tags": [
  "docker",
  "CAdvisor"
 ],
 "time": { "from": "2024-01-19T02:42:17.882Z", "to": "2024-01-19T02:49:26.267Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Running containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{id=~\"/system.slice/docker-.*\"})"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_last_seen{id=~\"/system.slice/docker-.*\"})/1024/1024"
    }
   ]
  },
  {
   "title": "Total CPU Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{id=~\"/system.slice/docker-.*\"}[15s]) * 100)"
    }
   ]
  },
  {
   "title": "Heap Size",
   "type": "timeseries",
   "description": "Measure of physical memory used by a process, including heap, stack, and shared libraries.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_rss{id=~\"/system.slice/docker-.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Heap Size Active",
   "type": "timeseries",
   "description": "Memory actively used by a process, often closely aligned with heap usage.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{id=~\"/system.slice/docker-.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{id=~\"/system.slice/docker-.*\"}[15s]) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 11 },
   "targets": [
    {
     "expr": "hour(time() - container_start_time_seconds{id=~\"/system.slice/docker-.*\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{id=~\"/system.slice/docker-.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Rx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{id=~\"/system.slice/docker-.*\"}[15s])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Tx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_transmit_bytes_total{id=~\"/system.slice/docker-.*\"}[15s])",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}