{
 "title": "NGINX",
 "description": "Official dashboard for NGINX Prometheus exporter",
 "tags": [
  "nginx",
  "prometheus",
  "nginx prometheus exporter"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": "label_values(nginx_up, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "NGINX Status for $instance",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_up{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_connections_active{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} active"
    },
    {
     "expr": "nginx_connections_writing{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} writing"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(nginx_http_requests_total{instance=~\"$instance\"}[15m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processed connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "irate(nginx_connections_accepted{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} accepted"
    },
    {
     "expr": "irate(nginx_connections_handled{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} handled"
    }
   ]
  }
 ]
}